import React, { useState } from 'react'
import { DataGrid } from '@mui/x-data-grid'
import Box from '@mui/material/Box'

const getImg = (params) => 
  <Box component='img' src={`images/${params.formattedValue}`} sx={{width: '100px'}} />

const columns = [
  { field: 'eventDate', headerName: 'EVENT DATE', flex: 1 },
  { field: 'eventName', headerName: 'EVENT NAME', flex: 1 },
  { field: 'bet', headerName: 'BET', flex: 1 },
  { field: 'marketType', headerName: 'MARKET TYPE', flex: 1 },
  { field: 'bookie', headerName: 'BOOKIE', flex: 1, renderCell: getImg },
  { field: 'backOdds', headerName: 'BACK ODDS', flex: 1 },
  { field: 'exchange', headerName: 'EXCHANGE', flex: 1, renderCell: getImg },
  { field: 'layOdds', headerName: 'LAY ODDS', flex: 1 },
  { field: 'rating', headerName: 'RATING', flex: 1 },
  { field: 'avail', headerName: 'AVAIL.', flex: 1 },
]

const rows = [
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
  {
    eventDate: '21/11/2022 09:00',
    eventName: 'Senegal vs Olanda',
    bet: 'Senegal',
    marketType: 'Match Odds',
    bookie: 'betgold.png',
    backOdds: '7.50',
    exchange: 'betfair.gif',
    layOdds: '34.00',
    rating: '22.06%',
    avail: '$11.93',
  },
]

const BettingTable = () => {
  const [ pageSize, setPageSize ] = useState(5)
  const handlePageSizeChange = (size) => {
    setPageSize(size)
  }
  return (
    <Box component="div" sx={{height: 111+pageSize*52, width: '100%'}}>
      <DataGrid
        rows={rows.map((value, index) => ({id: index + 1, ...value}))}
        columns={columns}
        pageSize={pageSize}
        onPageSizeChange={handlePageSizeChange}
        rowsPerPageOptions={[5, 10, 20]}
        checkboxSelection
      />
    </Box>
  )
}

export default BettingTable