# Generated by Django 4.0.6 on 2022-07-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bettingtable', '0003_user_active_user_admin_user_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
