# Generated by Django 4.0.6 on 2022-07-21 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bettingtable', '0004_remove_user_active_remove_user_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashid',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
